version: '3.8'

services:
  cafe-bot:
    build: .
    image: cafe-des-artistes:latest
    container_name: cafe-bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - JAVA_TOOL_OPTIONS=-XX:+UseZGC -XX:MaxRAMPercentage=75.0
    ports:
      - "8080:8080"
    labels:
      - "traefik.enable=false"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  prometheus:
    image: prom/prometheus:latest
    container_name: cafe-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    labels:
      - "traefik.enable=false"
    depends_on:
      - cafe-bot

volumes:
  prometheus_data: