version: '3.8'

services:
  bot-app:
    build:
      context: .
      dockerfile: infra-config/Dockerfile.bot-app
    depends_on:
      - rabbitmq
      - database
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - DATABASE_URL=jdbc:h2:tcp://database:9092/./data/bot

  bot-core:
    build:
      context: .
      dockerfile: infra-config/Dockerfile.bot-core
    depends_on:
      - rabbitmq
      - database
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - DATABASE_URL=jdbc:h2:tcp://database:9092/./data/bot

  bot-player:
    build:
      context: .
      dockerfile: infra-config/Dockerfile.bot-player
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/

  rabbitmq:
    image: rabbitmq:3-management

  database:
    image: oscarfonts/h2:latest