version: '3.8'

services:
  cafe-bot:
    build: .
    image: cafe-des-artistes:latest
    container_name: cafe-bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - JAVA_TOOL_OPTIONS=${BOT_JAVA_OPTS:-XX:+UseZGC -XX:MaxRAMPercentage=75.0}
    ports:
      - "${BOT_PORT:-8080}:8080"
    labels:
      - "traefik.enable=false"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      lavalink:
        condition: service_healthy

  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4.0.7
    container_name: cafe-lavalink
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=${LAVALINK_JAVA_OPTS:--Xmx1G}
      - SERVER_PORT=${LAVALINK_PORT:-2333}
      - LAVALINK_SERVER_PASSWORD=${LAVALINK_PASSWORD:-youshallnotpass}
    volumes:
      - ./lavalink.yml:/opt/Lavalink/application.yml:ro
    ports:
      - "${LAVALINK_PORT:-2333}:${LAVALINK_PORT:-2333}"
    labels:
      - "traefik.enable=false"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "--header=Authorization: youshallnotpass", "http://localhost:2333/version"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  prometheus:
    image: prom/prometheus:latest
    container_name: cafe-prometheus
    restart: unless-stopped
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    labels:
      - "traefik.enable=false"
    depends_on:
      - cafe-bot
      - lavalink

volumes:
  prometheus_data: