global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'cafe-bot'
    static_configs:
      - targets: ['cafe-bot:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s